export const ErrorCode = {
  // Auth
  AUTH_EMAIL_EXISTS: 'AUTH_EMAIL_EXISTS',
  AUTH_EMAIL_EXISTS_DIFFERENT_PROVIDER: 'AUTH_EMAIL_EXISTS_DIFFERENT_PROVIDER',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_BANNED: 'AUTH_ACCOUNT_BANNED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_REVOKED: 'AUTH_TOKEN_REVOKED',
  AUTH_RESET_TOKEN_INVALID: 'AUTH_RESET_TOKEN_INVALID',
  AUTH_GOOGLE_NO_EMAIL: 'AUTH_GOOGLE_NO_EMAIL',

  // Museum
  MUSEUM_NOT_FOUND: 'MUSEUM_NOT_FOUND',
  MUSEUM_INACTIVE: 'MUSEUM_INACTIVE',
  MUSEUM_SLUG_EXISTS: 'MUSEUM_SLUG_EXISTS',

  // Artifact
  ARTIFACT_NOT_FOUND: 'ARTIFACT_NOT_FOUND',

  // QR
  QR_INVALID_SIGNATURE: 'QR_INVALID_SIGNATURE',
  QR_DEACTIVATED: 'QR_DEACTIVATED',
  QR_NOT_FOUND: 'QR_NOT_FOUND',

  // Game
  GAME_SESSION_NOT_FOUND: 'GAME_SESSION_NOT_FOUND',
  GAME_SESSION_EXPIRED: 'GAME_SESSION_EXPIRED',
  GAME_SESSION_COMPLETED: 'GAME_SESSION_COMPLETED',

  // Quiz
  QUIZ_SESSION_NOT_FOUND: 'QUIZ_SESSION_NOT_FOUND',

  // AI
  AI_RATE_LIMIT_EXCEEDED: 'AI_RATE_LIMIT_EXCEEDED',
  AI_CONTENT_BLOCKED: 'AI_CONTENT_BLOCKED',

  // Users
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_BANNED: 'USER_BANNED',
  USER_ROLE_ESCALATION_FORBIDDEN: 'USER_ROLE_ESCALATION_FORBIDDEN',

  // General
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
